name: dictapi
version: 0.1.1
description: APIs to communicate with DICT servers.
author: Justin Andresen <jan.dresen.95@gmail.com>
homepage: https://github.com/just95/DICT.dart
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  args: ^0.13.3
  di: ^3.3.7
  path: ^1.3.9
  petitparser: ^1.5.1
  quiver: ^0.21.4
  redstone: ^0.6.5
  resource: ^1.1.0
  shelf: ^0.6.5
